auto_scroll_on_scoring: true
colors:
  accent_color: '#007bff'
  alternate_color: '#D2691E'
keybindings:
  custom_1: A
  custom_10: ;
  custom_2: S
  custom_3: D
  custom_4: F
  custom_5: G
  custom_6: H
  custom_7: J
  custom_8: K
  custom_9: L
  discard: BACKSPACE
  image_next: Right
  image_previous: Left
  score_4_up: H
  score_5_up: G
  score_6_up: F
  score_7_up: D
  score_8_up: S
  score_9: A
treat_categories_as_scoring: false
use_copy_custom: true
use_copy_default: false
