colors:
  accent_color: '#5a9bd8'
  add_color: '#6b8e6b'
  alternate_color: '#b08463'
  select_color: '#8c949a'
  warning_color: '#d93f00'
keybindings:
  key_0: A # score_9
  key_1: S # score_8_up
  key_2: D # score_7_up
  key_3: F # score_6_up
  key_4: G # score_5_up
  key_5: H # score_7_up
  key_6: J
  key_7: K
  key_8: L
  key_9: ;
  discard: BACKSPACE
  image_next: Right
  image_previous: Left
options:
  auto_scroll_on_scoring: true
  hide_scored_images: true
  write_to_filesystem: false
